### ISSUE TITLE
Tela de mapa não funciona

### ISSUE THREAD

**Issue by hudds** [projeto-monitoria-recycle-app/recycle-app#3]
Ao clicar sobre o ecoponto deveria abrir um mapa apontando a sua localização. Porém o que a aparece é um mapa em branco como na imagem abaixo:
![Screenshot from 2021-03-25 22-37-16](https://user-images.githubusercontent.com/34278912/112564856-c694b500-8dba-11eb-8eb2-7ce21ceceada.png)

 Analisando os logs do flutter no momento em que o mapa abre, identifiquei o seguinte: 
`E/Google Maps Android API( 6532): Authorization failure.  Please see https://developers.google.com/maps/documentation/android-api/start for how to correctly set up the map.`
`E/Google Maps Android API( 6532): In the Google Developer Console (https://console.developers.google.com)`
`E/Google Maps Android API( 6532): Ensure that the "Google Maps Android API v2" is enabled.`
`E/Google Maps Android API( 6532): Ensure that the following Android Key exists:`
`E/Google Maps Android API( 6532): 	API Key: GEO_API_KEY`
`E/Google Maps Android API( 6532): 	Android Application (<cert_fingerprint>;<package_name>): CB:24:45:DE:D8:A5:C4:CE:CE:4A:A4:76:47:B7:78:72:7F:41:7D:D9;com.example.recicle_app`

Aparentemente o bug é causado pela falta de uma chave para a API do google maps.

Identifiquei esse bug em um Xiaomi Note 8 com a MIUI 12.0.4, e também em um aparelho com Android 10 emulado no Android Studio.

**Comment by ThalesAzevedo** [comment]
Corrigida a falha pela hotfix/v1.0.1
